services:
  mysql:
    image: mysql:8.0
    container_name: eodi-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: eodi_app
      MYSQL_PASSWORD: eodi_app_pw
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init-scripts:/docker-entrypoint-initdb.d # 초기화 SQL 실행 경로
    command: --default-authentication-plugin=mysql_native_password

volumes:
  mysql_data: