import { formatWon } from "@/app/search/_util/util";

const NET_LEASABLE_AREA_OPTION = [33, 66, 99, 132, 165, 198, 231];

export const createInitialFilters = () => ({
  sell: {
    price: {
      key: "sell-price",
      label: "가격",
      valueFormatter: formatWon,
      step: 5000,
      enable: false,
      enableMin: true,
      enableMax: true,
      minValue: 50_000,
      maxValue: 100_000,
      min: 0,
      max: 200_000,
      type: "slider",
    },
    netLeasableArea: {
      key: "sell-netLeasableArea",
      label: "전용면적",
      valueFormatter: (v) => `${v}㎡`,
      enable: false,
      options: NET_LEASABLE_AREA_OPTION,
      enableMin: false,
      enableMax: false,
      minIndex: 0,
      maxIndex: 2,
      type: "discrete-slider",
    },
  },
  lease: {
    deposit: {
      key: "lease-deposit",
      label: "보증금",
      valueFormatter: formatWon,
      step: 1000,
      enable: false,
      enableMin: true,
      enableMax: true,
      minValue: 10_000,
      maxValue: 50_000,
      min: 0,
      max: 10_000_000,
      type: "slider",
    },
    monthlyRent: {
      key: "lease-monthlyRent",
      label: "월세",
      valueFormatter: formatWon,
      step: 50,
      enable: false,
      enableMin: true,
      enableMax: true,
      minValue: 20,
      maxValue: 100,
      min: 0,
      max: 100_000,
      type: "slider",
    },
    netLeasableArea: {
      key: "lease-netLeasableArea",
      label: "전용면적",
      valueFormatter: (v) => `${v}㎡`,
      enable: false,
      options: NET_LEASABLE_AREA_OPTION,
      enableMin: false,
      enableMax: false,
      minIndex: 0,
      maxIndex: 2,
      type: "discrete-slider",
    },
  },
});
